# 异常与断言

## 一、基础知识

- 异常概念
- Java异常类
  - Throwable接口为所有异常类的基类，Error和Exception直接继承于Throwable，RuntimeException和IOException直接继承于Exception
  - Error: 表示虚拟机或硬件异常，通常无法处理
  - RuntimeException: 表示由于编程错误引发的异常，如数组越界、空指针、零除。应使用非异常机制的编程手段处理
  - IOException: 一般是由于外界环境引发的异常，如文件不存在，字节流读取完毕
  - 非检查型异常和检查型异常
    - 非检查型异常: Error、RuntimeException
    - 检查型异常: IOException
- 异常发生的情形
  - 调用一个会抛出异常的方法
  - 检测到错误时使用throw关键字抛出一个检查型异常
  - 编程错误
  - 虚拟机运行发生错误  
- 异常声明
  - Java方法抛出异常必须使用异常声明，且只抛出声明指定的异常。如果遇到其它错误会直接终止程序
  - 语法: `修饰符 返回值 方法名(参数列表) throws Exception1, Exception, ..., Exceptionk`
  - 使用建议
    - 对于已定义的方法，异常声明指出了可能发生哪些异常
    - 对于自定义方法，建议只声明检查型异常。所有程序都可能触发Error异常，RuntimeException如无必要应当预先修正
  - 示例

    ```Java
    void drawImage(int i) throws FileNotFoundException, EOFException;  // good
    void drawImage(int i) throws ArrayIndexOutOfBoundsException;       // bad
    ```
  - 继承: 如果子类覆盖了超类的方法，覆盖方法可以不抛处或抛出更特定的异常，但不能抛出比超类更通用的异常
  - main方法内抛出异常但不处理时需要给main方法加异常声明

- 抛出异常与自定义异常类
- 捕获并处理异常


## 二、抛出异常与自定义异常类

- 抛出异常
  - 说明: 自定义方法抛出异常需使用异常声明，并在发出错误的位置使用throw抛出一个异常对象。调用方法发生异常时将抛出一个异常对象
  - 示例: 

    ```Java
    // 读取非空文件字符并打印，并在遇到EOF处抛出异常
    import java.io.File;
    import java.io.IOException;
    import java.io.EOFException;
    import java.io.FileNotFoundException;
    import java.io.FileWriter;
    import java.io.FileReader;

    public class RDTest {
        public static void main(String[] args) throws IOException{
            File f = new File("./message.txt");
            if (!f.exists()) f.createNewFile();
            FileWriter fw = new FileWriter(f);
            fw.write("This is a message to throw IOException.");
            fw.flush();
            fw.close();

            readData(f);
        }

        // 输入一个合法文本文件对象
        public static void readData(File file) throws EOFException, FileNotFoundException , IOException {
            FileReader fr = new FileReader(file);
            int c;
            while (true) {
                c = fr.read();
                if (c!=-1) 
                    System.out.println((char)c);
                else
                    throw EOFException();
            }
        }
    }
    ```

- 自定义异常
  - 继承Exception或子类可自定义异常，一般会定义一个默认构造器和包含错误信息的构造器
  - 示例代码

    ```java
    // 文件格式错误异常类
    import java.io.IOException;

    public class FileFormatException {
        public FileFormatException() {}
        public FileFormatException(String gribe) {
            super(gribe);
        }
    }
    ```

## 三、捕获并处理异常

- 处理机制
  - 当存在一个可能发生异常的代码块时，使用try进行标记
  - `catch(Type e){}`表示一个异常处理程序，一个try块可以有零个或多个catch块
  - 当try抛出一个异常对象时，程序将回退到try开始寻找最匹配的catch块，执行异常处理程序

- catch块
  - 语法: `catch(Type1| Type2| Type3 e) {}`
  - Java中一个catch块可以处理多个不同的类型
  - catch块中可以再次抛出异常，如果不进行处理，外围方法应当有该异常的声明

- finally与try-with-sources
  - finally: 即使异常发生，finally内语句仍可执行，一般用于释放资源。不要在finally内放改变流程控制的语句(return, continue, break, throw)
  - try-with-sources
    - 功能：当try执行完毕后会自动释放资源
    - 示例

      ```Java
      File f = new File("./text.txt");
      try (FileReader fr = new FileReader(f)) {
        // 语句块执行结束后会自动调用fr.close()
      }
      ```

## 四、断言

- 功能: 在测试期间对程序的内部错误进行检查
- 语法
  - `assert condition;` 或 `assert condition: expression;`
  - 当执行assert时，若为真则执行下一条语句；若condition为假则抛出一个AssertionError，若存在表达式则将表达式传递给构造器并最终转化为一个字符串
- 启用和关闭断言
  - 断言默认状态下是关闭的
  - -enableassertion/-ea，-disableassertion/-da用于启动或关闭非系统类断言
  - -enablesystemassertion/-esa，-disablesystemassertion/-dsa用于启动或关闭系统类断言
  - 可以选择启用或关闭所有、某个包、某个类的断言
  - 示例 

    ```Java
    java -ea MyApp  //启用所有断言
    java -ea:MyClass -ea:com.mycompany.mylib MyApp  //启用某个类或某个包的断言
    ```

